### ISSUE TITLE
Read the object

### ISSUE THREAD

**Issue by Ruochen1105** [CSCI-GA-2820-SP24-003/recommendations#1]
As a recommendation manager
I need the ability to Read the relationship between two items
So that I can make recommendation decisions based on the relationship
   
 ### Details and Assumptions

- The relationship of items will be stored in a database
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given there are some relationships in the database
 When I query the relationship of two items
 Then I get a float or a Null
```

**Comment by huangiris17** [comment]
Implementation to be discussed: Recommendations should have a recommendation type like cross-sell, up-sell, accessory, etc. should use Python enumerations to represent the different recommendation types
