### ISSUE TITLE
Add "Create" Button to UI

### ISSUE THREAD

**Issue by Ruochen1105** [CSCI-GA-2820-SP24-003/recommendations#31]
**As a** recommendation manager
**I need** a "Create" button in the UI
**So that** I can use the UI to create recommendations
   
 ### Details and Assumptions
 * In the UI there would be a "Create" button
 * There might be input boxes neighboring the "Create" button
 * Clicking the "Create" button uses the information in the input boxes to perform the "Create"
 * There should be a BDD test for the "Create" button
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I fill in the input boxes with legit data
 When I click the "Create" button
 Then a new object is inserted in to the DB
```

 ```gherkin
 Given I fill in the input boxes with problematic data
 When I click the "Create" button
 Then I get an alert to check the input data
```

**Comment by OlekKapera** [comment]
@huangiris17 Are you working on this issue? I see you change the status to `In Progress` but didn't assign yourself to this issue.
