### ISSUE TITLE
Setup RedHat OpenShift for deployment

### ISSUE THREAD

**Issue by Ruochen1105** [CSCI-GA-2820-SP24-003/recommendations#63]
**As a** developer
**I need** the cloud setup
**So that** I can deploy the service to the cloud
   
 ### Details and Assumptions
- RedHat OpenShift will provide kubernetes services
- Manually deploy PostgreSQL to your cluster
- Create a route to your microservice
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the RedHat OpenShift is setup
When I deploy my service to the cloud
Then the service is running on the cloud
```

**Comment by henryhu-zh** [comment]
Link: https://recommendations-henryhu-zh-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/
